proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=img_cache:10m max_size=1g inactive=30d use_temp_path=off;

server {
    listen 80;
    server_name localhost;

    # Proxy uploads request to NestJS backend on host
    location /uploads/ {
        proxy_pass http://host.docker.internal:4000/media/uploads/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # CORS headers are handled by NestJS backend
        
        # Increase timeouts to prevent "upstream timed out" during heavy load
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        # Server-Side Cache Settings
        proxy_cache img_cache;
        proxy_cache_valid 200 365d;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;
        proxy_cache_lock on;

        # Enable caching for images
        expires 365d;
        add_header Cache-Control "public, no-transform, immutable";
        add_header X-Proxy-Cache $upstream_cache_status;
    }
}
